name: Gemini Action on Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  run_gemini_action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    if: 
      contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/gemini')
    steps:
      - name: Run Gemini Action
        uses: strawgate/gemini-for-github@main
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_number: ${{ github.event.issue.number }}
          user_question: ${{ github.event.comment.body }}