name: Gemini Action on Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  run_gemini_action:
    runs-on: ubuntu-latest
    if: 
      contains(github.event.comment.body, '/gemini')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Gemini Action
        uses: strawgate/gemini-for-github@main
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_number: ${{ github.event.pull_request.number }}
          github_issue_number: ${{ github.event.issue.number }}
          user_question: ${{ github.event.comment.body }}