name: Gemini Action on Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  run_gemini_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gemini Action
        uses: strawgate/gemini-for-github@0.1.0
        with:
          github_repository: ${{ github.repository }}
          github_owner: ${{ github.repository_owner }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_issue_number: ${{ github.event.issue.number }}
          user_question: ${{ github.event.comment.body }}